In [1]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
corpus = []

with open("text_content.txt") as f:
    for line in f:
        corpus.append(line.rstrip())
print(corpus)
X = vectorizer.fit_transform(corpus)

print(X.toarray())

print(vectorizer.get_feature_names())

['SITEN te sege and te assaut watz sesed at Troye,', 'Te bor? brittened and brent to bronde? and askez,', 'Te tulk tat te trammes of tresoun ter wro?t', 'Watz tried for his tricherie, te trewest on erthe:', 'Hit watz Ennias te athel, and his highe kynde,', 'Tat siten depreced prouinces, and patrounes bicome', 'Welne?e of al te wele in te west iles.', 'Fro riche Romulus to Rome ricchis hym swyte,', 'With gret bobbaunce tat bur?e he biges vpon fyrst,', 'And neuenes hit his aune nome, as hit now hat;']
[[0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 1 1 0 0 2 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0]
 [0 2 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0
  0 0 0 0 0 0 0 0 0 0 1 2 1 0 1 1 0 0 0 0 1 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
  0 0 0 0 0 0 

In [4]:
import pandas as pd
from pandas import DataFrame

In [5]:
DataFrame(X.toarray(), columns=vectorizer.get_feature_names())

al  and  as  askez  assaut  at  athel  aune  bicome  biges ...   tried  \
0   0    1   0      0       1   1      0     0       0      0 ...       0   
1   0    2   0      1       0   0      0     0       0      0 ...       0   
2   0    0   0      0       0   0      0     0       0      0 ...       0   
3   0    0   0      0       0   0      0     0       0      0 ...       1   
4   0    1   0      0       0   0      1     0       0      0 ...       0   
5   0    1   0      0       0   0      0     0       1      0 ...       0   
6   1    0   0      0       0   0      0     0       0      0 ...       0   
7   0    0   0      0       0   0      0     0       0      0 ...       0   
8   0    0   0      0       0   0      0     0       0      1 ...       0   
9   0    1   1      0       0   0      0     1       0      0 ...       0   

   troye  tulk  vpon  watz  wele  welne  west  with  wro  
0      1     0     0     1     0      0     0     0    0  
1      0     0     0     0     0      0     0     0    0  
2      0     1     0     0     0      0     0     0    1  
3      0     0     0     1     0      0     0     0    0  
4      0     0     0     1     0      0     0     0    0  
5      0     0     0     0     0      0     0     0    0  
6      0     0     0     0     1      1     1     0    0  
7      0     0     0     0     0      0     0     0    0  
8      0     0     1     0     0      0     0     1    0  
9      0     0     0     0     0      0     0     0    0  

[10 rows x 65 columns]

In [6]:
import numpy as np

In [8]:
X = np.random.randint(2, size=(6, 100))
X

array([[0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
        0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
        0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
        0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
        1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1,
        0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
        1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        0, 0, 0, 0, 0,

In [10]:
Y = np.array([1, 2, 3, 4, 4, 5])
Y

array([1, 2, 3, 4, 4, 5])

In [11]:
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()

In [12]:
clf.fit(X, Y)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [13]:
clf.predict(X[2:3])

array([3])

In [14]:
X = np.random.randint(2, size=(6, 100)) 
X

array([[0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1,
        0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0,
        1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1,
        0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
        1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
        1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
        1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
        0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
        0, 0, 0, 0, 1,