In [90]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
np.set_printoptions(precision=4)

In [91]:
df = pd.DataFrame([  
            ['green', 'M', 10.1, 'class1'],   
            ['red', 'L', 13.5, 'class2'],   
            ['blue', 'XL', 15.3, 'class1']])  
df.columns = ['color', 'size', 'prize', 'class label']  
df

color size  prize class label
0  green    M   10.1      class1
1    red    L   13.5      class2
2   blue   XL   15.3      class1

In [92]:
size_mapping = {  
           'XL': 3,  
           'L': 2,  
           'M': 1}  
df['size'] = df['size'].map(size_mapping) 
df

color  size  prize class label
0  green     1   10.1      class1
1    red     2   13.5      class2
2   blue     3   15.3      class1

In [93]:
# -----------------------------------------------
# 使用 pd.get_dummies() 进行处理
pd.get_dummies(df)

size  prize  color_blue  color_green  color_red  class label_class1  \
0     1   10.1           0            1          0                   1   
1     2   13.5           0            0          1                   0   
2     3   15.3           1            0          0                   1   

   class label_class2  
0                   0  
1                   1  
2                   0

In [94]:
df

color  size  prize class label
0  green     1   10.1      class1
1    red     2   13.5      class2
2   blue     3   15.3      class1

In [95]:
# -----------------------------------------------
# 使用  sklearn.feature_extraction.DictVectorizer 进行处理
feature_list = []
label_list = []
for row in df.index[:]:
    label_list.append(df.ix[row][-1])
    rowDict = {}
    for i in range(0, len(df.ix[row])-1):
        rowDict[df.columns[i]] = df.ix[row][i]
    feature_list.append(rowDict)
feature_list

[{'color': 'green', 'prize': 10.1, 'size': 1},
 {'color': 'red', 'prize': 13.5, 'size': 2},
 {'color': 'blue', 'prize': 15.300000000000001, 'size': 3}]

In [96]:
label_list

['class1', 'class2', 'class1']

In [97]:
from sklearn.feature_extraction import DictVectorizer
vec = DictVectorizer()
# DictVectorizer.fit_transform() 接受一个由 dict 组成的 list
dummy_x = vec.fit_transform(feature_list).toarray()
dummy_x

array([[  0. ,   1. ,   0. ,  10.1,   1. ],
       [  0. ,   0. ,   1. ,  13.5,   2. ],
       [  1. ,   0. ,   0. ,  15.3,   3. ]])

In [98]:
from sklearn import preprocessing
label_bin = preprocessing.LabelBinarizer()
# preprocessing.LabelBinarizer.fit_transform() 接受一个 list
dummy_y = label_bin.fit_transform(label_list)
dummy_y

array([[0],
       [1],
       [0]])

In [99]:
# 测试 当 label 种类大于 2 的时候的效果
df['class label'][2] = 'class3'
df

C:\Users\rHotD\Anaconda3\lib\site-packages\ipykernel\__main__.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app


color  size  prize class label
0  green     1   10.1      class1
1    red     2   13.5      class2
2   blue     3   15.3      class3

In [100]:
feature_list = []
label_list = []
for row in df.index[:]:
    label_list.append(df.ix[row][-1])
    rowDict = {}
    for i in range(0, len(df.ix[row])-1):
        rowDict[df.columns[i]] = df.ix[row][i]
    feature_list.append(rowDict)
dummy_y = label_bin.fit_transform(label_list)
dummy_y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [ ]:
# 结论，两者效果差不多一样，但是 pd.get_dummies 更好用一些