In [3]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [9]:
group = DataFrame([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]], columns=['feature_1', 'feature_2'])
group

feature_1  feature_2
0        1.0        1.1
1        1.0        1.0
2        0.0        0.0
3        0.0        0.1

In [11]:
labels = DataFrame(['A','A','B','B'], columns=['labels'])
labels

labels
0      A
1      A
2      B
3      B

In [17]:
# 效果相同
# data_set = pd.merge(group, labels, how='outer', left_index=True, right_index=True)
data_set = group.join(labels)
data_set

feature_1  feature_2 labels
0        1.0        1.1      A
1        1.0        1.0      A
2        0.0        0.0      B
3        0.0        0.1      B

In [18]:
data_set['feature_1']

0    1.0
1    1.0
2    0.0
3    0.0
Name: feature_1, dtype: float64

In [19]:
data_set.ix[0]

feature_1      1
feature_2    1.1
labels         A
Name: 0, dtype: object

In [20]:
data_set['feature_1'][0]

1.0

In [22]:
data_set.ix[0]['feature_1']

1.0

In [24]:
data_set.iloc[0]

feature_1      1
feature_2    1.1
labels         A
Name: 0, dtype: object

In [25]:
data_set.iloc[0, :]

feature_1      1
feature_2    1.1
labels         A
Name: 0, dtype: object

In [26]:
data_set.iloc[:, 0]

0    1.0
1    1.0
2    0.0
3    0.0
Name: feature_1, dtype: float64

In [27]:
data_set.iloc[:, 0].values

array([ 1.,  1.,  0.,  0.])

In [29]:
data_set.shape

(4, 3)

In [30]:
len(data_set.columns)

3

In [31]:
data_set.values

array([[1.0, 1.1, 'A'],
       [1.0, 1.0, 'A'],
       [0.0, 0.0, 'B'],
       [0.0, 0.1, 'B']], dtype=object)

In [33]:
data_set.iloc[:, :2].values

array([[ 1. ,  1.1],
       [ 1. ,  1. ],
       [ 0. ,  0. ],
       [ 0. ,  0.1]])

In [28]:
def createDataSet():
    group = DataFrame([[1.0,1.1],[1.0,1.0],[0,0],[0,0.1]], columns=['feature_1', 'feature_2'])
    labels = DataFrame(['A','A','B','B'], columns=['labels'])
    data_set = group.join(labels)
    return data_set
createDataSet()

feature_1  feature_2 labels
0        1.0        1.1      A
1        1.0        1.0      A
2        0.0        0.0      B
3        0.0        0.1      B